export const ele = [
  {
    id: 1,
    name: "Twitter Clone",
    description:"A Twitter clone project is a social media web application that allows users to create an account, post short messages known as 'tweets' follow other users, and receive updates from those they follow. The platform mimics the key features of Twitter, providing a similar user experience for those who want to communicate and share their thoughts and ideas in real-time. The project involves building the frontend and backend of the application, designing a database schema to store user information and tweets, implementing user authentication and authorization, and deploying the application to a web server. Additional features such as direct messaging, retweeting, and hashtags may also be added to enhance the user experience. Overall, the Twitter clone project is a challenging and rewarding way to develop one's web development skills and gain experience building a full-stack web application.",
    image: "url('twitter.jpg')",
    repo: "https://github.com/serAnkii/web3_twitter",
    deploy: "/",
    context: "Full-stack web development project",
    role: "From Scratch to hatch",
    skills: ["React", "FireBase", "CSS"],
    outcome: "Developed a fully functional social media platform with key features similar to Twitter",
    visuals: ["/block.jpeg", "/credit.jpeg", "/eyeback.jpg"]
  },
  {
    id: 2,
    name: "protfolio website",
    description:"As a professional seeking to showcase my skills and experience, a portfolio website project is a great way to create a visually appealing and interactive platform. I set clear goals and objectives for my project, while designing a user-friendly website that highlights my accomplishments. I gathered inspiration from other portfolio websites in my field, paid close attention to the details, and showcased my expertise to potential clients or employers. Overall, my portfolio website project is an essential tool for building my reputation online and attracting new opportunities.",
    image: "url('portfolio.png')",
    repo: "https://github.com/serAnkii/portfolio-website/",
    deploy: "/",
    context: "Personal portfolio website project",
    role: "Sole developer",
    skills: ["React", "CSS", "HTML"],
    outcome: "Developed a visually appealing and interactive platform to showcase my skills and experience",
    visuals: ["Homepage", "Projects page", "About page"]
  },
  {
    id: 3,
    name: "Automated attendence system",
    description:"The face recognition attendance system project involves developing an automated system that uses facial recognition technology to track attendance. The project requires designing a user-friendly interface that can recognize faces and record attendance in real-time. The system utilizes OpenCV and deep learning techniques to improve accuracy and reliability. Attendance records are automatically captured and stored in a database, allowing administrators to view records and generate reports. Testing and optimization are essential to ensure that the system works correctly and accurately. Overall, the face recognition attendance system project is a great way to streamline attendance tracking and enhance security in various organizations.",
    image: "url('facerecog.png')",
    repo: "https://github.com/serAnkii/projectface",
    deploy: "/",
    context: "Object Detection project",
    role: "sole developer",
    skills: ["Python", "OpenCV"],
    outcome: "Developed an automated system to track attendance using facial recognition technology",
    visuals: ["User interface", "Attendance records dashboard"]
  },
  {
    id: 4,
    name: "credit card fraud detection",
    description:"The credit card fraud detection project involves developing an automated system that can detect and prevent fraudulent transactions in real-time. The system utilizes machine learning techniques to analyze transaction data and flag potential fraud. The system is designed to reduce false positives and false negatives, ensuring accuracy and reliability. The system requires ongoing maintenance and updates to remain effective in detecting and preventing fraud. Overall, the credit card fraud detection project is a critical component of enhancing security and protecting customers from financial losses.",
    image: "url('credit.jpeg')",
    repo: "https://github.com/serAnkii/Credit_Card_fraud_detection",
    deploy: "",
  },
  {
    id: 5,
    name: "Blockchain Based Supply Chain",
    description:"This project aims to use blockchain technology to create a more transparent and efficient food distribution system. It will connect farmers, distributors, retailers, and consumers in a decentralized platform, improving traceability and accountability in the food supply chain.",
    image: "url('block.jpeg')",
    repo: "",
    deploy: "",
    shadowcolor: "rgb(182 23 23)",
  },
  {
    id: 6,
    name: "tic-tac-toe game",
    description:
    "The Tic-Tac-Toe game project involves creating a fun and engaging game that is easy to play and understand. The project requires designing a user-friendly interface that allows players to easily select their moves and track the progress of the game. The game can be developed using different programming languages, frameworks, and libraries. Testing and debugging are essential to ensure that the game is free from bugs and working correctly. Overall, the Tic-Tac-Toe game project is a great way to showcase programming skills and provide a fun experience for players.",
    image: "url('tic-tac-toe.png')",
    repo: "https://github.com/serAnkii/javascript/tree/main/Projects/Tic-tac-toe",
    deploy: "",
    shadowcolor: "orange",
  },
];
