export const images = [
  { id: 0, name: "cpp", primary_url: "icons/c-plus-plus.svg" ,secondary_url:"icons/c-plus-plus.svg"},
  { id: 1, name: "java", primary_url: "icons/java.svg" ,secondary_url:"icons/java.gif"},
  { id: 15, name: "Python", primary_url: "icons/python.svg" ,secondary_url:"icons/Python.gif"},
  { id: 2, name: "html", primary_url: "icons/html.svg" ,secondary_url:"icons/Html.gif"},
  { id: 3, name: "css", primary_url: "icons/css3.svg" ,secondary_url:"icons/Css.gif"},
  { id: 4, name: "sass", primary_url: "icons/sass.svg" ,secondary_url:"icons/Sass.gif"},
  { id: 5, name: "tailwind-css", primary_url: "icons/tailwind-css.svg" ,secondary_url:"icons/tailwind-css.svg"},
  { id: 6, name: "javaScript", primary_url: "icons/javascript.svg" ,secondary_url:"icons/Javascript.gif"},
  { id: 7, name: "jquery", primary_url: "icons/jquery.svg" ,secondary_url:"icons/jquery.svg"},
  { id: 8, name: "react.js", primary_url: "icons/react.svg" ,secondary_url:"icons/React.gif"},
  { id: 9, name: "redux", primary_url: "icons/redux.svg" ,secondary_url:"icons/redux.svg"},
  { id: 10, name: "node.js", primary_url: "icons/nodejs.svg" ,secondary_url:"icons/Nodejs.gif"},
  { id: 11, name: "php", primary_url: "icons/php.svg" ,secondary_url:"icons/Php.gif"},
  { id: 12, name: "mongoDB", primary_url: "icons/mongodb.svg" ,secondary_url:"icons/mongodb.svg"},
  { id: 13, name: "mysql", primary_url: "icons/mysql.svg" ,secondary_url:"icons/Mysql.gif"},
  { id: 14, name: "blockchain", primary_url: "icons/blockchain.svg" ,secondary_url:"icons/blockchain.svg"},
  { id: 15, name: "git", primary_url: "icons/git.svg" ,secondary_url:"icons/git.svg"},
];
